services:
    schemaspy:
        container_name: schemaspy
        image: schemaspy/schemaspy:6.1.0
        user: root
        volumes:
        -   ./sqlite-jdbc-3.36.0.3.jar:/driver.jar
        -   ./schemaspy.properties:/schemaspy.properties
        -   ../source/extras/schemaspy/:/output/
        -   ../../ridbpy/data/ridb.db:/ridb.db
        command:
        -   java
        -   -jar
        -   schemaspy-6.1.0.jar
        -   -configFile
        -   /schemaspy.properties
        -   -hq
        -   -debug
        entrypoint: []
