name: 'Dependabot Batcher: Scheduled'
on:
    schedule:
    -   cron: 0 9 * * 1,3
    workflow_dispatch:

jobs:
    dependabot-batcher:
        runs-on: ubuntu-latest
        steps:
        -   name: Combine Dependabot PRs
            uses: Legal-and-General/dependabot-batcher@v1.0.2
            token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
            batchBranchName: ci/dependabot/batcher/updates
            batchPullTitle: 'Dependabot 🤖: Batcher Updates'
